# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ImageView' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ImageView

  target 'ImageViewTests' do
    inherit! :search_paths
    # Pods for testing
pod 'Alamofire'
  end

  target 'ImageViewUITests' do
    # Pods for testing
  end

end
